#!/bin/bash
# /etc/init.d/reprasp

### BEGIN INIT INFO
# Provides:          reprasp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: reprasp initscript
# Description:       This service is used to manage reprasp controller
### END INIT INFO


case "$1" in 
    start)
        echo "Starting reprasp! Woo Hoo!"
        cd /home/pi/RepRasp && /usr/local/bin/grunt connect:server
        ;;
    stop)
        echo "Stopping servoblaster"
        killall reprasp
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac

exit 0